version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: post-it-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./secrets:/run/secrets
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/password
    networks:
      - post-it

  server:
    container_name: post-it-server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:5000"
    volumes:
      - ./secrets:/usr/src/secrets/
      - ./frontend/dist:/usr/src/frontend/dist
    networks:
      - post-it

networks:
  post-it:

volumes:
  db-data:
